/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import excecoes.MFPException;
import excecoes.PDException;
import excecoes.PEException;
import excecoes.PIException;
import excecoes.SIException;
import excecoes.UJCException;
import java.util.Arrays;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import mytwitter.MyTwitter;
import mytwitter.perfil.Perfil;
import mytwitter.perfil.PessoaFisica;
import mytwitter.perfil.tweet.Tweet;

/**
 *
 * @author anderson
 */
public class interfaceMyTwitter extends javax.swing.JFrame {

    /**
     * Creates new form interfaceMyTwitter
     */
    public interfaceMyTwitter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelBuscar = new javax.swing.JLabel();
        textoProcurarUsuario = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoCriarPerfil = new javax.swing.JTextField();
        bCriarPerfil = new javax.swing.JButton();
        bSeguir = new javax.swing.JButton();
        bTimeline = new javax.swing.JButton();
        bCancelarPerfil = new javax.swing.JButton();
        textoSeguir = new javax.swing.JTextField();
        textoUsuarioSeguir = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoUsuario = new javax.swing.JLabel();
        bTweetar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoTweetAtual = new javax.swing.JEditorPane();
        lista = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBuscar.setText("Procurar usuário");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Criar Perfil");

        bCriarPerfil.setText("Criar");
        bCriarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriarPerfilActionPerformed(evt);
            }
        });

        bSeguir.setText("Seguir");
        bSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeguirActionPerformed(evt);
            }
        });

        bTimeline.setText("Timeline");
        bTimeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTimelineActionPerformed(evt);
            }
        });

        bCancelarPerfil.setText("Cancelar Perfil");
        bCancelarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarPerfilActionPerformed(evt);
            }
        });

        textoSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSeguirActionPerformed(evt);
            }
        });

        textoUsuarioSeguir.setText("Usuário: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoProcurarUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(labelBuscar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(bBuscar)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(bCriarPerfil))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bTimeline)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoUsuarioSeguir)
                                            .addComponent(bSeguir))))))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bCancelarPerfil)
                            .addComponent(textoSeguir, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(textoCriarPerfil))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelBuscar)
                .addGap(18, 18, 18)
                .addComponent(textoProcurarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBuscar)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textoCriarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCriarPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoUsuarioSeguir)
                .addGap(15, 15, 15)
                .addComponent(bSeguir)
                .addGap(18, 18, 18)
                .addComponent(bTimeline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bCancelarPerfil)
                .addContainerGap())
        );

        textoUsuario.setText("Nome: ");

        bTweetar.setText("Tweetar");
        bTweetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTweetarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(textoTweetAtual);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoUsuario)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bTweetar))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bTweetar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        String nome = textoProcurarUsuario.getText();
        if(nome.isEmpty()){
            return;
        } else {
            perfilUsuario = rede.getRepositorio().buscar(nome);
            if(perfilUsuario == null){
                System.out.println("Não há usuário.");
                textoProcurarUsuario.setText("");
                lista.removeAll();
                textoSeguir.setText("");
                return;
            } else{
                textoProcurarUsuario.setText("");
                textoUsuario.setText("Usuário: " + nome);
                System.out.println(perfilUsuario.getUsuario());
                return;
            }
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bCriarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriarPerfilActionPerformed
        try{
           String nome = textoCriarPerfil.getText();
           if(nome.isEmpty()){
               return;
           } else {
               rede.criarPerfil(new PessoaFisica(nome));
               textoCriarPerfil.setText("");
           }
        } catch (PEException ex) {
            System.out.println("Já existe um perfil com esse nome de usuário.");
            textoCriarPerfil.setText("");
        } catch (UJCException ex) {
            System.out.println("Já existe um Usuário com esse nome.");
            textoCriarPerfil.setText("");
        }
    }//GEN-LAST:event_bCriarPerfilActionPerformed

    private void bSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeguirActionPerformed
        try{
        String nome = textoSeguir.getText();
        if(nome.isEmpty()){
               return;
           } else {
               rede.seguir(perfilUsuario.getUsuario(), nome);
               textoSeguir.setText("");
               textoUsuarioSeguir.setText(nome);
           }
        } catch (PIException ex) {
            System.out.println("Perfil Inexistente!");
        } catch (PDException ex) {
            System.out.println("Perfil desativado!");
        } catch (SIException ex) {
           System.out.println("Seguidor Inexistente!");
        } 
    }//GEN-LAST:event_bSeguirActionPerformed

    private void bTimelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTimelineActionPerformed
        try {
            Tweet[] vetor = rede.mostrar(rede.timeline(perfilUsuario.getUsuario()));
            for(int i = 0; i < vetor.length; i++){
                lista.add(vetor[i].getMensagem() + "    \n" + vetor[i].getHora().get(Calendar.HOUR_OF_DAY) + ":" + vetor[i].getHora().get(Calendar.MINUTE)+ ":" + vetor[i].getHora().get(Calendar.SECOND) + " " + vetor[i].getHora().get(Calendar.DAY_OF_MONTH) + "/" + vetor[i].getHora().get(Calendar.MONTH)+ "/" + vetor[i].getHora().get(Calendar.YEAR));
            }
        } catch (PIException ex) {
            System.out.println("Perfil Inexistente!");
        } catch (PDException ex) {
            System.out.println("Perfil já desativado!");
        }
    }//GEN-LAST:event_bTimelineActionPerformed

    private void bCancelarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarPerfilActionPerformed
        try {
            rede.cancelarPerfil(perfilUsuario.getUsuario());
        } catch (PIException ex) {
            System.out.println("Perfil Inexistente!");
        } catch (PDException ex) {
            System.out.println("Perfil já desativado!");
        }
    }//GEN-LAST:event_bCancelarPerfilActionPerformed

    private void bTweetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTweetarActionPerformed
        try {
            rede.tweetar(perfilUsuario.getUsuario(), textoTweetAtual.getText());
            textoTweetAtual.setText("");
            lista.removeAll();
            for(int i = rede.tweets(perfilUsuario.getUsuario()).size() - 1; i >= 0; i--){
                lista.add(rede.tweets(perfilUsuario.getUsuario()).get(i).getMensagem());
            }
        } catch (PIException ex) {
            System.out.println("Perfil Inexistente!");
        } catch (MFPException ex) {
            System.out.println("Mensagem fora do padrão!");
        } catch (PDException ex) {
             System.out.println("Perfil desativado!");
        }
    }//GEN-LAST:event_bTweetarActionPerformed

    private void textoSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSeguirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSeguirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceMyTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceMyTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceMyTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceMyTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceMyTwitter().setVisible(true);
            }
        });
    }
    MyTwitter rede = new MyTwitter();
    Perfil perfilUsuario;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCancelarPerfil;
    private javax.swing.JButton bCriarPerfil;
    private javax.swing.JButton bSeguir;
    private javax.swing.JButton bTimeline;
    private javax.swing.JButton bTweetar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBuscar;
    private java.awt.List lista;
    private javax.swing.JTextField textoCriarPerfil;
    private javax.swing.JTextField textoProcurarUsuario;
    private javax.swing.JTextField textoSeguir;
    private javax.swing.JEditorPane textoTweetAtual;
    private javax.swing.JLabel textoUsuario;
    private javax.swing.JLabel textoUsuarioSeguir;
    // End of variables declaration//GEN-END:variables
}
