package interfaceGrafica;

import excecoes.MFPException;
import excecoes.PDException;
import excecoes.PEException;
import excecoes.PIException;
import excecoes.SIException;
import excecoes.UJCException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import mytwitter.MyTwitter;
import mytwitter.perfil.Perfil;
import mytwitter.perfil.PessoaFisica;
import mytwitter.perfil.PessoaJuridica;
import mytwitter.perfil.tweet.Tweet;


public class interfaceMyTwitter extends javax.swing.JFrame {

    /**
     * Creates new form interfaceMyTwitter
     */
    public interfaceMyTwitter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        textoProcurarUsuario = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoCriarPerfil = new javax.swing.JTextField();
        bCriarPerfil = new javax.swing.JButton();
        bSeguir = new javax.swing.JButton();
        textoUsuarioSeguir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bPessoaFisica = new javax.swing.JRadioButton();
        bPessoaJuridica = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        textoInfo = new javax.swing.JLabel();
        textoCpfCnpj = new javax.swing.JTextField();
        labelBuscar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        avisoProcurar = new javax.swing.JLabel();
        avisoCriar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoUsuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoTweetAtual = new javax.swing.JEditorPane();
        bTimeline = new javax.swing.JButton();
        textoStatus = new javax.swing.JLabel();
        seguindo = new java.awt.List();
        jSeparator3 = new javax.swing.JSeparator();
        avisoPerfilAtual = new javax.swing.JLabel();
        lista = new java.awt.List();
        jLabel4 = new javax.swing.JLabel();
        seguidores = new java.awt.List();
        jLabel6 = new javax.swing.JLabel();
        bTweetar = new javax.swing.JButton();
        textoTrocar = new javax.swing.JTextField();
        bTrocar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        avisoTroca = new javax.swing.JLabel();
        bCancelarPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoProcurarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoProcurarUsuarioActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Criar Perfil");

        textoCriarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCriarPerfilActionPerformed(evt);
            }
        });

        bCriarPerfil.setText("Criar");
        bCriarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriarPerfilActionPerformed(evt);
            }
        });

        bSeguir.setText("Seguir");
        bSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeguirActionPerformed(evt);
            }
        });

        textoUsuarioSeguir.setText("Usuário: ");

        jLabel2.setText("Nome:");

        buttonGroup1.add(bPessoaFisica);
        bPessoaFisica.setText("Pessoa Física");
        bPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPessoaFisicaActionPerformed(evt);
            }
        });

        buttonGroup1.add(bPessoaJuridica);
        bPessoaJuridica.setText("Pessoa Jurídica");
        bPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPessoaJuridicaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de conta: ");

        textoInfo.setText("Info:");

        labelBuscar.setText("Procurar usuário");

        avisoProcurar.setText("Aviso: ");

        avisoCriar.setText("Aviso: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(textoCriarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBuscar)
                                    .addComponent(textoProcurarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bPessoaJuridica)
                                            .addComponent(bPessoaFisica)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(textoInfo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bCriarPerfil)
                                                    .addComponent(textoCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(avisoCriar)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bBuscar)
                                    .addComponent(textoUsuarioSeguir)
                                    .addComponent(bSeguir))))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(avisoProcurar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCriarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPessoaFisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPessoaJuridica)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoInfo)
                    .addComponent(textoCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCriarPerfil)
                .addGap(18, 18, 18)
                .addComponent(avisoCriar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBuscar)
                .addGap(18, 18, 18)
                .addComponent(textoProcurarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoUsuarioSeguir)
                .addGap(18, 18, 18)
                .addComponent(bSeguir)
                .addGap(12, 12, 12)
                .addComponent(avisoProcurar)
                .addContainerGap())
        );

        textoUsuario.setText("Nome: ");

        jScrollPane2.setViewportView(textoTweetAtual);

        bTimeline.setText("Mostrar Timeline");
        bTimeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTimelineActionPerformed(evt);
            }
        });

        textoStatus.setText("Status:");

        avisoPerfilAtual.setText("Aviso: ");

        jLabel4.setText("Seguindo");

        jLabel6.setText("Seguidores");

        bTweetar.setText("Tweetar");
        bTweetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTweetarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(seguindo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoUsuario)
                                    .addComponent(textoStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(bTweetar)))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTimeline)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avisoPerfilAtual)
                            .addComponent(jLabel6)
                            .addComponent(seguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bTweetar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoStatus)))
                .addGap(22, 22, 22)
                .addComponent(avisoPerfilAtual)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seguindo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bTimeline)
                        .addGap(43, 43, 43))))
        );

        textoTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTrocarActionPerformed(evt);
            }
        });

        bTrocar.setText("Trocar");
        bTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTrocarActionPerformed(evt);
            }
        });

        jLabel5.setText("Trocar de Usuário: ");

        avisoTroca.setText("Aviso: ");

        bCancelarPerfil.setText("Cancelar Perfil");
        bCancelarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(avisoTroca))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoTrocar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(bTrocar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bCancelarPerfil)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoTrocar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTrocar)
                            .addComponent(bCancelarPerfil))
                        .addGap(18, 18, 18)
                        .addComponent(avisoTroca)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTimelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTimelineActionPerformed
        try {
            lista.removeAll();
            Tweet[] vetor = rede.mostrar(rede.timeline(perfilUsuario2.getUsuario()));
            for(int i = 0; i < vetor.length; i++){
                lista.add(vetor[i].getUsuario() + ": " + vetor[i].getMensagem() + " | " + vetor[i].getHora().get(Calendar.HOUR_OF_DAY) + ":" + vetor[i].getHora().get(Calendar.MINUTE)+ ":" + vetor[i].getHora().get(Calendar.SECOND) + " " + vetor[i].getHora().get(Calendar.DAY_OF_MONTH) + "/" + vetor[i].getHora().get(Calendar.MONTH)+ "/" + vetor[i].getHora().get(Calendar.YEAR));
            }
        } catch (PIException ex) {
            avisoPerfilAtual.setText("Aviso: Perfil Inexistente!");
        } catch (PDException ex) {
            avisoPerfilAtual.setText("Aviso: Perfil já desativado!");
        }
    }//GEN-LAST:event_bTimelineActionPerformed

    private void bCancelarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarPerfilActionPerformed
        try {
            rede.cancelarPerfil(perfilUsuario2.getUsuario());
            textoStatus.setText("Status: " + perfilUsuario2.isAtivo());
        } catch (PIException ex) {
            avisoPerfilAtual.setText("Aviso: Perfil Inexistente!");
        } catch (PDException ex) {
            avisoPerfilAtual.setText("Aviso: Perfil já desativado!");
        }
    }//GEN-LAST:event_bCancelarPerfilActionPerformed

    private void bTweetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTweetarActionPerformed
        try {
            rede.tweetar(perfilUsuario2.getUsuario(), textoTweetAtual.getText());
            textoTweetAtual.setText("");
            lista.removeAll();
            for(int i = rede.tweets(perfilUsuario2.getUsuario()).size() - 1; i >= 0; i--){
                lista.add(rede.tweets(perfilUsuario2.getUsuario()).get(i).getMensagem() + " |  " + rede.tweets(perfilUsuario2.getUsuario()).get(i).getHora().get(Calendar.HOUR_OF_DAY) + ":" + rede.tweets(perfilUsuario2.getUsuario()).get(i).getHora().get(Calendar.MINUTE) + ":" + rede.tweets(perfilUsuario2.getUsuario()).get(i).getHora().get(Calendar.SECOND) + " " + rede.tweets(perfilUsuario2.getUsuario()).get(i).getHora().get(Calendar.DAY_OF_MONTH) + "/" + rede.tweets(perfilUsuario2.getUsuario()).get(i).getHora().get(Calendar.MONTH) + "/" + rede.tweets(perfilUsuario2.getUsuario()).get(i).getHora().get(Calendar.YEAR));
            }
        } catch (PIException ex) {
            avisoPerfilAtual.setText("Aviso: Perfil Inexistente!");
        } catch (MFPException ex) {
            avisoPerfilAtual.setText("Aviso: Mensagem fora do padrão!");
        } catch (PDException ex) {
            avisoPerfilAtual.setText("Aviso: Perfil já desativado!");
        }
    }//GEN-LAST:event_bTweetarActionPerformed

    private void bSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeguirActionPerformed
        try{
            rede.seguir(perfilUsuario2.getUsuario(), perfilUsuario1.getUsuario());
            textoProcurarUsuario.setText("");
            textoUsuarioSeguir.setText(perfilUsuario1.getUsuario());
        } catch (PIException ex) {
            avisoProcurar.setText("Aviso: Perfil Inexistente!");
        } catch (PDException ex) {
            avisoProcurar.setText("Aviso: Perfil desativado!");
        } catch (SIException ex) {
            avisoProcurar.setText("Aviso: Seguidor Inexistente!");
        }
    }//GEN-LAST:event_bSeguirActionPerformed

    private void bCriarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriarPerfilActionPerformed
        try{
            String nome = textoCriarPerfil.getText();
            if(nome.isEmpty() || (!bPessoaFisica.isSelected() && !bPessoaJuridica.isSelected()) || textoCpfCnpj.getText().isEmpty()){
                return;
            } else {
                if(bPessoaFisica.isSelected()){
                    perfilPF = new PessoaFisica(nome);
                    try {
                        perfilPF.setCpf(Long.valueOf(textoCpfCnpj.getText()).longValue());
                        rede.criarPerfil(perfilPF);
                        textoCriarPerfil.setText("");
                        textoCpfCnpj.setText("");
                        avisoCriar.setText("Aviso: Usuário " + perfilPF.getUsuario() + " criado!");
                    } catch (NumberFormatException ex){
                        avisoCriar.setText("Aviso: Digite apenas números!");
                        textoCriarPerfil.setText("");
                        textoCpfCnpj.setText("");
                    }
                } else {
                    perfilPJ = new PessoaJuridica(nome);
                    try {
                        perfilPJ.setCnpj(Long.valueOf(textoCpfCnpj.getText()).longValue());
                        rede.criarPerfil(perfilPJ);
                        textoCriarPerfil.setText("");
                        textoCpfCnpj.setText("");
                        avisoCriar.setText("Aviso: Usuário " + perfilPJ.getUsuario() + " criado!");
                    } catch(NumberFormatException ex){
                        avisoCriar.setText("Aviso: Digite apenas números!");
                        textoCriarPerfil.setText("");
                        textoCpfCnpj.setText("");
                    }
                }        
            }
        } catch (PEException ex) {
            avisoCriar.setText("Aviso: Já existe um perfil com esse nome!");
            textoCriarPerfil.setText("");
            textoCpfCnpj.setText("");
        } catch (UJCException ex) {
            avisoCriar.setText("Aviso: Já existe um Usuário com esse nome!");
            textoCriarPerfil.setText("");
            textoCpfCnpj.setText("");
        }
    }//GEN-LAST:event_bCriarPerfilActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        String nome = textoProcurarUsuario.getText();
        if(nome.isEmpty()){
            return;
        } else {
            perfilUsuario1 = rede.getRepositorio().buscar(nome);
            if(perfilUsuario1 == null){
                avisoProcurar.setText("Não há usuário");
                textoProcurarUsuario.setText("");
                return;
            } else{
                textoProcurarUsuario.setText("");
                textoUsuarioSeguir.setText("Usuário: " + nome);
                System.out.println(perfilUsuario1.getUsuario());
                return;
            }
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void textoProcurarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoProcurarUsuarioActionPerformed
    }//GEN-LAST:event_textoProcurarUsuarioActionPerformed

    private void textoCriarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCriarPerfilActionPerformed
    }//GEN-LAST:event_textoCriarPerfilActionPerformed

    private void bPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPessoaFisicaActionPerformed
         textoInfo.setText("CPF: ");
    }//GEN-LAST:event_bPessoaFisicaActionPerformed

    private void bPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPessoaJuridicaActionPerformed
        textoInfo.setText("CNPJ: ");
    }//GEN-LAST:event_bPessoaJuridicaActionPerformed

    private void bTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrocarActionPerformed
        String nome = textoTrocar.getText();
        if(nome.isEmpty()){
            return;
        } else {
            perfilUsuario2 = rede.getRepositorio().buscar(nome);
            if(perfilUsuario2 == null || !(perfilUsuario2.isAtivo())){
                textoTrocar.setText("");
                lista.removeAll();
                seguidores.removeAll();
                seguindo.removeAll();
                return;
            } else{
                textoTrocar.setText("");
                textoUsuario.setText("Usuário: " + nome);
                textoStatus.setText("Status: " + perfilUsuario2.isAtivo());
                seguidores.removeAll();
                seguindo.removeAll();
                for(int i = 0; i < perfilUsuario2.getSeguidores().size(); i++){
                    seguidores.add((perfilUsuario2.getSeguidores()).get(i));
                }
                for(int j = 0; j < perfilUsuario2.getSeguindo().size(); j++){
                    seguindo.add(perfilUsuario2.getSeguindo().get(j));
                }    
                lista.removeAll();
                return;
            }
        }
    }//GEN-LAST:event_bTrocarActionPerformed

    private void textoTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTrocarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTrocarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceMyTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceMyTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceMyTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceMyTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceMyTwitter().setVisible(true);
            }
        });
    }
    MyTwitter rede = new MyTwitter();
    Perfil perfilUsuario1;
    Perfil perfilUsuario2;
    PessoaFisica perfilPF;
    PessoaJuridica perfilPJ;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoCriar;
    private javax.swing.JLabel avisoPerfilAtual;
    private javax.swing.JLabel avisoProcurar;
    private javax.swing.JLabel avisoTroca;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCancelarPerfil;
    private javax.swing.JButton bCriarPerfil;
    private javax.swing.JRadioButton bPessoaFisica;
    private javax.swing.JRadioButton bPessoaJuridica;
    private javax.swing.JButton bSeguir;
    private javax.swing.JButton bTimeline;
    private javax.swing.JButton bTrocar;
    private javax.swing.JButton bTweetar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelBuscar;
    private java.awt.List lista;
    private java.awt.List seguidores;
    private java.awt.List seguindo;
    private javax.swing.JTextField textoCpfCnpj;
    private javax.swing.JTextField textoCriarPerfil;
    private javax.swing.JLabel textoInfo;
    private javax.swing.JTextField textoProcurarUsuario;
    private javax.swing.JLabel textoStatus;
    private javax.swing.JTextField textoTrocar;
    private javax.swing.JEditorPane textoTweetAtual;
    private javax.swing.JLabel textoUsuario;
    private javax.swing.JLabel textoUsuarioSeguir;
    // End of variables declaration//GEN-END:variables
}
